In [5]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.sentiment import SentimentIntensityAnalyzer

In [6]:
df  = pd.read_csv("C:\\Deep Learning\\NLP\\Sentiment_analysis.csv")

In [7]:
sia = SentimentIntensityAnalyzer()

In [8]:
df.head(3)

,Text,Sentiment,Source,Date/Time,User ID,Location,Confidence Score
0,I love this product!,Positive,Twitter,2023-06-15 09:23:14,@user123,New York,0.85
1,The service was terrible.,Negative,Yelp Reviews,2023-06-15 11:45:32,user456,Los Angeles,0.65
2,This movie is amazing!,Positive,IMDb,2023-06-15 14:10:22,moviefan789,London,0.92

In [9]:
def scores(text):
    score =  sia.polarity_scores(text)['compound']
    if score >= 0.05:
        return "Posivite"
    elif score <= -0.05:
        return "Negative"
    else:
        return "Neutral"

In [10]:
df['Text_score'] = df['Text'].apply(scores)

In [11]:
df.head(10)

,Text,Sentiment,Source,Date/Time,User ID,Location,Confidence Score,Text_score
0,I love this product!,Positive,Twitter,2023-06-15 09:23:14,@user123,New York,0.85,Posivite
1,The service was terrible.,Negative,Yelp Reviews,2023-06-15 11:45:32,user456,Los Angeles,0.65,Negative
2,This movie is amazing!,Positive,IMDb,2023-06-15 14:10:22,moviefan789,London,0.92,Posivite
3,I'm so disappointed with their customer support.,Negative,Online Forum,2023-06-15 17:35:11,forumuser1,Toronto,0.78,Negative
4,Just had the best meal of my life!,Positive,TripAdvisor,2023-06-16 08:50:59,foodie22,Paris,0.88,Posivite
5,The quality of this product is subpar.,Negative,Amazon Reviews,2023-06-16 10:15:27,shopper123,San Francisco,0.72,Neutral
6,I can't stop listening to this song. It's incr...,Positive,Spotify,2023-06-16 13:40:18,musiclover456,Berlin,0.91,Posivite
7,Their website is so user-friendly. Love it!,Positive,Website Testimonial,2023-06-16 16:05:36,testimonialuser1,Sydney,0.87,Posivite
8,I loved the movie! It was fantastic!,Positive,IMDb,2023-07-02 09:12:34,user123,New York,0.92,Posivite
9,The customer service was terrible.,Negative,Yelp Reviews,2023-07-02 10:45:21,user456,Los Angeles,0.65,Negative